# Generated by Django 6.0 on 2025-12-21 18:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turbine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TurbineLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('turbine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.turbine')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OnTurbineReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rotor_speed', models.FloatField(blank=True, null=True)),
                ('power_output', models.FloatField(blank=True, null=True)),
                ('generator_temperature', models.FloatField(blank=True, null=True)),
                ('gearbox_oil_temperature', models.FloatField(blank=True, null=True)),
                ('gearbox_oil_pressure', models.FloatField(blank=True, null=True)),
                ('vibration_level', models.FloatField(blank=True, null=True)),
                ('blade_pitch_angle', models.FloatField(blank=True, null=True)),
                ('yaw_position', models.FloatField(blank=True, null=True)),
                ('yaw_error', models.FloatField(blank=True, null=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_turbine_readings', to='core.turbinelog')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('scheduled', 'Scheduled'), ('repair', 'Repair'), ('failure', 'Failure'), ('inspection', 'Inspection'), ('replacement', 'Replacement')], max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('parts_replaced', models.TextField(blank=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('turbine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_events', to='core.turbine')),
                ('log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_events', to='core.turbinelog')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='HealthPrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('health_score', models.FloatField()),
                ('failure_probability', models.FloatField()),
                ('predicted_failure_window_start', models.DateTimeField(blank=True, null=True)),
                ('predicted_failure_window_end', models.DateTimeField(blank=True, null=True)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('features_used', models.JSONField(blank=True, default=dict)),
                ('turbine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_predictions', to='core.turbine')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='core.turbinelog')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WeatherReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('wind_direction', models.FloatField(blank=True, null=True)),
                ('wave_height', models.FloatField(blank=True, null=True)),
                ('wave_period', models.FloatField(blank=True, null=True)),
                ('water_temperature', models.FloatField(blank=True, null=True)),
                ('air_temperature', models.FloatField(blank=True, null=True)),
                ('air_humidity', models.FloatField(blank=True, null=True)),
                ('lightning_strikes', models.IntegerField(default=0)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_readings', to='core.turbinelog')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=20)),
                ('message', models.TextField()),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='core.healthprediction')),
                ('turbine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.turbine')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['turbine', '-created_at'], name='core_alert_turbine_a7733d_idx'), models.Index(fields=['severity', 'acknowledged'], name='core_alert_severit_8b60b4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='turbinelog',
            index=models.Index(fields=['turbine', '-timestamp'], name='core_turbin_turbine_06679a_idx'),
        ),
        migrations.AddIndex(
            model_name='onturbinereading',
            index=models.Index(fields=['log'], name='core_onturb_log_id_c51c3f_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceevent',
            index=models.Index(fields=['turbine', '-start_time'], name='core_mainte_turbine_9c968c_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceevent',
            index=models.Index(fields=['event_type'], name='core_mainte_event_t_881c00_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceevent',
            index=models.Index(fields=['log'], name='core_mainte_log_id_b83445_idx'),
        ),
        migrations.AddIndex(
            model_name='healthprediction',
            index=models.Index(fields=['turbine', '-timestamp'], name='core_health_turbine_2cd0e8_idx'),
        ),
        migrations.AddIndex(
            model_name='healthprediction',
            index=models.Index(fields=['failure_probability'], name='core_health_failure_587731_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherreading',
            index=models.Index(fields=['log'], name='core_weathe_log_id_505a8e_idx'),
        ),
    ]
