# Generated by Django 6.0 on 2026-01-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_status_to_turbine'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='is_dummy_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprediction',
            name='is_dummy_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenanceevent',
            name='is_dummy_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onturbinereading',
            name='is_dummy_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turbine',
            name='is_dummy_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turbinelog',
            name='is_dummy_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weatherreading',
            name='is_dummy_data',
            field=models.BooleanField(default=False),
        ),
    ]
