# Generated by Django 6.0.1 on 2026-01-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_is_dummy_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onturbinereading',
            name='is_dummy_data',
        ),
        migrations.RemoveField(
            model_name='turbine',
            name='is_dummy_data',
        ),
        migrations.AddField(
            model_name='onturbinereading',
            name='current_l1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onturbinereading',
            name='current_l2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onturbinereading',
            name='current_l3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onturbinereading',
            name='front_bearing_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onturbinereading',
            name='gear_oil_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onturbinereading',
            name='gearbox_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onturbinereading',
            name='generator_rpm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onturbinereading',
            name='nacelle_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onturbinereading',
            name='power_factor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onturbinereading',
            name='reactive_power',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onturbinereading',
            name='rear_bearing_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onturbinereading',
            name='rotor_speed_rpm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onturbinereading',
            name='torque',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onturbinereading',
            name='transformer_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onturbinereading',
            name='voltage_l1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onturbinereading',
            name='voltage_l2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onturbinereading',
            name='voltage_l3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onturbinereading',
            name='wind_direction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onturbinereading',
            name='wind_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turbine',
            name='status',
            field=models.CharField(choices=[('operational', 'Operational'), ('maintenance', 'Under Maintenance'), ('fault', 'Fault'), ('offline', 'Offline')], default='operational', max_length=20),
        ),
    ]
